### ISSUE TITLE
The lo_cpp.h header contains out of class definitions

### ISSUE THREAD

**Issue by rafalcieslak** [radarsat1/liblo#23]
It is currently impossible to use the lo_cpp.h header in two different translation units. Each time lo_cpp.h is included, it imports a few functions, which results in multiple definitions.

*Example*:

a.h:
```c++
#ifndef AH
#define AH
#include <lo_cpp.h>
void func(lo::Message);  
#endif AH
```
a.cpp
```c++
#include "a.h"
void func(lo::Message){
  ....
}
```
b.cpp
```c++
#include "a.h"
int main(){
  func(...);
}
```

Compilation succeeds, linking fails, because the following functions have double definitions:

```c++
std::string version();
lo_timetag now();
lo_timetag immediate();
int Address::send_from(lo::ServerThread &from, const string_type &path, const string_type &type, ...);
int Address::send_from(lo::ServerThread &from, lo_bundle b);
```

and indeed that is the case, as these functions have out of class definitions inside lo_cpp.h. This is wrong, as that is not the point of header files.

No in-source tests are detecting this issue, because they all use a single translation unit.

Possible solution would be to convert these definitions into in-class definitions, if possible. Another option would be to move these definitions to a separate header file, which would be then included on developer's demand. Yet another solution would be to wrap these definitions in a preprocesor #ifndef directive, so that it is possible to manualy deactivate them.

I believe this bug is of high severity, beause it makes it impossible to use the C++ liblo API in any serious application that is made of more than a single file. A temporary workaround is to remove the offending function definitions from the header file.

**Comment by radarsat1** [comment]
Haha, wow, rookie mistake, I'm surprised this went undiscovered for so long!  Fixed by marking the affected functions as "inline" in 3713b9944cceeae04d87cfd251e50fe175021945.  (This was the original intention anyways -- C++ wrapper functions are meant to be short and sweet and inlined.)

**Comment by Wallacoloo** [comment]
@radarsat1 I notice this hasn't been patched on the liblo under source control at Sourceforge, yet you are maintainer of the project there. Can you also submit the patch there, or is the Sourceforge repository officially deprecated?

If the later, I would recommend redirecting users to the git repo on the Sourceforge [project page](https://sourceforge.net/projects/liblo/) if it's not too much trouble.

**Comment by radarsat1** [comment]
Forgot to push, sorry.

**Comment by sdegrande** [comment]
We still have the same issue on Fedora (I did not check on the other distros), mainly because you did not release a new version. 
Fedora liblo package is thus still based on the 0.28 tarball, which pre-dates your fix.
Could you please release a more recent version of your lib ?
Thx a lot for your work, I use your lib in a lot of applications !

**Comment by radarsat1** [comment]
Done

**Comment by showlabor** [comment]
Thank you very much! I've added a note about the new release to the existing bug in Red Hat's bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1283120

**Comment by sdegrande** [comment]
Thanks for the release !

**Comment by radarsat1** [comment]
Thanks for reminding me.. sorry it took so long  😂
